#!/usr/bin/env bash

image=$(mktemp)
grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name') $image
convert $image -blur 0x8 $image
swaylock \
    -efr \
    -i $image \
    --indicator-radius 100 \
    --indicator-thickness 20 \
    --inside-color 00000033
rm $image
